### PR TITLE
Fix for gluon master

### PR DESCRIPTION
**Pull request by MTRNord**
This Pull should first be merged when the actual master is stable. With GLUONDIR it fails. This works.

### CODE REVIEW

**Comment by bdobe** [comment]
Should "include $(INCLUDE_DIR)/package.mk" not be better?

**Comment by MTRNord** [comment]
Should also work i think :) in the gluon master commit the version I am using was used.

**Comment by MTRNord** [comment]
If needed I will change that of course or just use this PR as info PR and close it ;)

**Comment by bdobe** [comment]
Fixed in https://github.com/freifunkhamburg/ffhh-packages/commit/ef9fcc1222f74c3c045b1450537a4b8b80efb56c

**Comment by MTRNord** [comment]
@bdobe talked to neoiraider in #gluon irc the correct include is now `include $(TOPDIR)/../package/gluon.mk`

**Pull request closed without merging**
